### PR TITLE
Fix return value if build fails

### LINKED ISSUE #19: goem build exit code
Looks like `geom build moep` returns an error code of 0, even if the build fails.

### PR DESCRIPTION
**Pull request by roa**
Fix #19

### CODE REVIEW

File: build.go [hunk 1]
```diff
@@ -34,7 +34,7 @@ func build(args []string) {
 
 	out, err := execBuild.CombinedOutput()
 	if err != nil {
-		fmt.Printf("%s\n", out)
+		stderrAndExit(errors.New(string(out)))
 	}
```
Comment (wellle) [inline build.go]: I don't know the full context here, but shouldn't it look something like this?
```go
if out, err := execBuild.CombinedOutput(); err != nil {
	stderrAndExit(err)
} else {
	fmt.Printf("%s\n", out)
}
```
